### PR TITLE
Added mod tools to Veinminer tool list

### PR DESCRIPTION
**Pull request by emberquill**
Added pickaxes, axes, and shovels from the following mods:
- Actually Additions (also added the AIOT to pickaxe, axe, and shovel lists)
- Base Metals and Modern Metals
- Biomes O'Plenty
- Psi
- Silent's Gems
- TechReborn
- Tinkers' Construct (also added the mattock to shovel and axe lists)

### CODE REVIEW

**Comment by emberquill** [comment]
I can add the drills and chainsaws from Actually Additions and TechReborn too, if you want. And I wasn't sure if Crack Hammers should be added to the pickaxe list or not, so I left them out.

**Comment by Lanse505** [comment]
Add the Drills, Chainsaws ^^ :+1:

**Comment by Lanse505** [comment]
Btw you have;
-        "techreborn:bronzeSpade",
  -        "techreborn:rubySpade",
  -        "techreborn:sapphireSpade",
  -        "techreborn:peridotSpade",

under your axes

**Comment by emberquill** [comment]
Ah, I pretty much copied the shovel list to the axe list, then did a find/replace "shovel" with "axe". I forgot that TechReborn used "Spade" instead. That's fixed.

EDIT: Also added chainsaws to axe list, and drills to pickaxe/shovel lists.

**Comment by Lanse505** [comment]
@EmberQuill This PR is now merged with the main branch of RR4

**Comment by StrayCargo** [comment]
Can I suggest if we do any more branch merges that we try to do them in a slough of them so we arent having to update the master so much

**Comment by Lanse505** [comment]
Tbh we're not gonna do many branch mergers. This was just the simplest way of me doing this without having to go to his branch, copy it over, make him delete his branch and generally causing a bunch of hassel.

**Comment by StrayCargo** [comment]
I understand just saying future times we can do this but suggest we do them in bundles

**Comment by Lanse505** [comment]
Agreed

**Comment by Lanse505** [comment]
If we get multiple PRs we bundle them
In cases like this were we only have 1 we just merge if possible

**Comment by StrayCargo** [comment]
ok

**Pull request merged**
